// Package runtime is keep's seam over the OS service runtime: the artifacts
// keep renders to disk and the control and observation operations it performs
// on the units those artifacts describe. Everything here speaks keep's
// vocabulary (CONTEXT.md) rather than any one runtime's; the launchd and, in
// future, systemd adapters translate (ADR-0008).
package runtime

import "context"

// State is the normalized live state of a unit as the runtime reports it.
type State string

const (
	// StateUnknown means the runtime does not know the label at all (launchd:
	// not bootstrapped). It is not the same as stopped: there is no unit to
	// stop.
	StateUnknown State = "unknown"
	// StateStopped means the runtime knows the unit and no process is live.
	StateStopped State = "stopped"
	// StateRunning means the unit has a live PID.
	StateRunning State = "running"
	// StateFailed means the last run exited non-zero and nothing is running.
	StateFailed State = "failed"
)

// Info is the live state of one unit.
type Info struct {
	State    State
	PID      int  // 0 unless State == StateRunning
	LastExit *int // nil when the runtime reports none
}

// Running reports whether the unit has a live process.
func (i Info) Running() bool { return i.State == StateRunning }

// Known reports whether the runtime tracks the unit at all.
func (i Info) Known() bool { return i.State != StateUnknown }

// Target identifies a Service's unit(s) to a verb. Scheduled lets an adapter
// route control to a different unit than the one it would use for a resident
// Service without having to probe disk.
type Target struct {
	Label     string
	Scheduled bool
}

// Artifact is one rendered file. launchd emits one per Service; other runtimes
// may emit more. The Manager, never the adapter, writes these.
type Artifact struct {
	Path string
	Data []byte
}

// MarkerInfo is what an adapter reads back out of a file on disk to decide
// whether keep generated it, and for which Service.
type MarkerInfo struct {
	Managed  bool
	Label    string // derived by the adapter from the path and/or the content
	Service  string
	KeepPath string
}

// Severity classifies a Diagnosis.
type Severity string

const (
	SevError   Severity = "error"
	SevWarning Severity = "warning"
	SevInfo    Severity = "info"
)

// Diagnosis is a read-only problem with the runtime environment itself, as
// opposed to any one Service.
type Diagnosis struct {
	Severity Severity
	Problem  string
	Fix      string
}

// Diagnoser is an optional Runtime capability: the health checks only an
// adapter can make, because only it knows what its runtime needs to work.
// `keep doctor` folds them in for an adapter that implements it and asks
// nothing of one that does not.
type Diagnoser interface {
	Diagnose() []Diagnosis
}

// Runtime is the one seam between keep's orchestration and an OS service
// runtime. Adapters own rendering, control, and observation; they never touch
// the filesystem.
type Runtime interface {
	// ArtifactDir is the directory the runtime loads generated artifacts from.
	ArtifactDir() string
	// Render produces every artifact for a Job. Deterministic: apply compares
	// regenerated bytes against what is on disk to stay idempotent.
	Render(job Job) []Artifact
	// ReadMarkers parses keep's markers out of a file the adapter may have
	// generated. Managed is false for anything the adapter does not recognize.
	ReadMarkers(path string, data []byte) MarkerInfo

	// Load makes the runtime track and start the unit(s) already on disk
	// (idempotent).
	Load(ctx context.Context, t Target) error
	// Unload stops the unit(s) and does not return until teardown has
	// completed, so the label is free to Load again (idempotent). ctx bounds
	// the wait, not the stop.
	Unload(ctx context.Context, t Target) error
	// Hold persistently disables the unit; it survives reboot and apply until
	// Release (ADR-0003).
	Hold(t Target) error
	// Release clears a Hold.
	Release(t Target) error
	// Start starts a loaded unit.
	Start(t Target) error
	// Restart restarts a loaded unit in place.
	Restart(t Target) error
	// Forget stops the units behind the given artifacts and clears every
	// persistent record of them. The paths are the artifact files keep is
	// removing, because a label is not always the right granularity: when a
	// Service gives up one of its files while another Service takes over
	// another under the same label, only the abandoned unit may be stopped.
	// Empty paths means the whole label, for a pruned Service whose artifacts
	// keep can no longer enumerate.
	Forget(ctx context.Context, label string, paths []string) error

	// Info returns the live state of the unit.
	Info(t Target) (Info, error)
	// Held returns label -> held for every unit the runtime holds.
	Held() (map[string]bool, error)
	// Uptime returns a human-readable elapsed time for a running PID, or "".
	Uptime(pid int) string
}
