// Package launchd renders generated artifacts (plists), drives launchctl, and
// parses its output. It is the only package that knows launchd's mechanics;
// everything above it speaks in Services, not jobs.
package launchd

import (
	"bytes"
	"encoding/xml"
	"fmt"
	"strings"
)

// Marker keys keep embeds in every generated plist so it can recognize its own
// artifacts independently of the label (D19). Unmanaged jobs never carry these.
const (
	MarkerKey     = "KeepManaged"
	ServiceKey    = "KeepService"
	VersionKey    = "KeepVersion"
	KeepPathKey   = "KeepPath"
	ManagedMarker = true
)

// Job is the fully-resolved description keep renders into a plist.
type Job struct {
	Label             string
	ProgramArguments  []string
	RunAtLoad         bool
	KeepAlive         bool
	StandardOutPath   string
	StandardErrorPath string
	StartInterval     int                // seconds; 0 == unset
	StartCalendar     []CalendarInterval // calendar fire times

	// Marker fields.
	Service     string
	KeepVersion string
	KeepPath    string
}

// CalendarInterval mirrors a StartCalendarInterval dict entry. Nil == any.
type CalendarInterval struct {
	Minute  *int
	Hour    *int
	Day     *int
	Weekday *int
	Month   *int
}

// Render produces deterministic plist XML for a Job. Determinism matters: apply
// compares regenerated bytes against the on-disk artifact to stay idempotent.
func Render(j Job) []byte {
	var b strings.Builder
	b.WriteString(`<?xml version="1.0" encoding="UTF-8"?>` + "\n")
	b.WriteString(`<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">` + "\n")
	b.WriteString(`<plist version="1.0">` + "\n")
	b.WriteString("<dict>\n")

	writeKeyString(&b, "Label", j.Label)
	writeKeyStringArray(&b, "ProgramArguments", j.ProgramArguments)
	if j.RunAtLoad {
		writeKeyBool(&b, "RunAtLoad", true)
	}
	if j.KeepAlive {
		writeKeyBool(&b, "KeepAlive", true)
	}
	if j.StandardOutPath != "" {
		writeKeyString(&b, "StandardOutPath", j.StandardOutPath)
	}
	if j.StandardErrorPath != "" {
		writeKeyString(&b, "StandardErrorPath", j.StandardErrorPath)
	}
	if j.StartInterval > 0 {
		writeKeyInt(&b, "StartInterval", j.StartInterval)
	}
	if len(j.StartCalendar) > 0 {
		writeKeyCalendar(&b, "StartCalendarInterval", j.StartCalendar)
	}

	// Managed marker — last, so it is easy to spot.
	writeKeyBool(&b, MarkerKey, ManagedMarker)
	writeKeyString(&b, ServiceKey, j.Service)
	if j.KeepVersion != "" {
		writeKeyString(&b, VersionKey, j.KeepVersion)
	}
	if j.KeepPath != "" {
		writeKeyString(&b, KeepPathKey, j.KeepPath)
	}

	b.WriteString("</dict>\n")
	b.WriteString("</plist>\n")
	return []byte(b.String())
}

func writeKeyString(b *strings.Builder, key, val string) {
	fmt.Fprintf(b, "\t<key>%s</key>\n\t<string>%s</string>\n", xmlEscape(key), xmlEscape(val))
}

func writeKeyInt(b *strings.Builder, key string, val int) {
	fmt.Fprintf(b, "\t<key>%s</key>\n\t<integer>%d</integer>\n", xmlEscape(key), val)
}

func writeKeyBool(b *strings.Builder, key string, val bool) {
	tag := "<false/>"
	if val {
		tag = "<true/>"
	}
	fmt.Fprintf(b, "\t<key>%s</key>\n\t%s\n", xmlEscape(key), tag)
}

func writeKeyStringArray(b *strings.Builder, key string, vals []string) {
	fmt.Fprintf(b, "\t<key>%s</key>\n\t<array>\n", xmlEscape(key))
	for _, v := range vals {
		fmt.Fprintf(b, "\t\t<string>%s</string>\n", xmlEscape(v))
	}
	b.WriteString("\t</array>\n")
}

func writeKeyCalendar(b *strings.Builder, key string, intervals []CalendarInterval) {
	fmt.Fprintf(b, "\t<key>%s</key>\n\t<array>\n", xmlEscape(key))
	for _, ci := range intervals {
		b.WriteString("\t\t<dict>\n")
		writeCalField(b, "Minute", ci.Minute)
		writeCalField(b, "Hour", ci.Hour)
		writeCalField(b, "Day", ci.Day)
		writeCalField(b, "Weekday", ci.Weekday)
		writeCalField(b, "Month", ci.Month)
		b.WriteString("\t\t</dict>\n")
	}
	b.WriteString("\t</array>\n")
}

func writeCalField(b *strings.Builder, name string, v *int) {
	if v == nil {
		return
	}
	fmt.Fprintf(b, "\t\t\t<key>%s</key>\n\t\t\t<integer>%d</integer>\n", name, *v)
}

func xmlEscape(s string) string {
	r := strings.NewReplacer(
		"&", "&amp;",
		"<", "&lt;",
		">", "&gt;",
	)
	return r.Replace(s)
}

// IsManaged reports whether plist bytes carry keep's managed marker.
func IsManaged(data []byte) bool {
	return ReadMarkers(data).Managed
}

// MarkerService extracts the embedded service name from managed plist bytes.
func MarkerService(data []byte) string {
	return ReadMarkers(data).Service
}

// MarkerKeepPath extracts the embedded pinned keep path from managed plist bytes.
func MarkerKeepPath(data []byte) string {
	return ReadMarkers(data).KeepPath
}

// MarkerInfo is the parsed keep marker embedded in a generated artifact.
type MarkerInfo struct {
	Managed  bool
	Service  string
	KeepPath string
}

// ReadMarkers parses all keep marker fields from plist bytes in one pass.
func ReadMarkers(data []byte) MarkerInfo {
	dec := xml.NewDecoder(bytes.NewReader(data))
	var out MarkerInfo
	for {
		key, ok := nextKey(dec)
		if !ok {
			return out
		}
		if readMarkerValue(dec, key, &out) && out.Managed && out.Service != "" && out.KeepPath != "" {
			return out
		}
	}
}

func nextKey(dec *xml.Decoder) (string, bool) {
	for {
		tok, err := dec.Token()
		if err != nil {
			return "", false
		}
		start, ok := tok.(xml.StartElement)
		if !ok || start.Name.Local != "key" {
			continue
		}
		var key string
		if err := dec.DecodeElement(&key, &start); err != nil {
			return "", false
		}
		return key, true
	}
}

func readMarkerValue(dec *xml.Decoder, key string, out *MarkerInfo) bool {
	for {
		tok, err := dec.Token()
		if err != nil {
			return false
		}
		start, ok := tok.(xml.StartElement)
		if !ok {
			continue
		}
		switch start.Name.Local {
		case "true":
			_ = dec.Skip()
			if key == MarkerKey {
				out.Managed = true
				return true
			}
		case "false":
			_ = dec.Skip()
			return key == MarkerKey
		case "string":
			var value string
			if err := dec.DecodeElement(&value, &start); err != nil {
				return false
			}
			switch key {
			case ServiceKey:
				out.Service = value
				return true
			case KeepPathKey:
				out.KeepPath = value
				return true
			}
		default:
			_ = dec.Skip()
		}
		return false
	}
}
